# Generated by Django 2.2 on 2019-04-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('region', models.CharField(choices=[('NS', 'Nur-Sultan'), ('AT', 'Aktau'), ('AL', 'Almaty'), ('SH', 'Shymkent'), ('KO', 'Kyzylorda'), ('KR', 'Karaganda'), ('ZK', 'Zhezkazgan'), ('KT', 'Kokshetau'), ('ZO', 'Zhanaozen'), ('OS', 'Oskemen'), ('OL', 'Oral'), ('SM', 'Semey'), ('PV', 'Pavlodar'), ('PT', 'Petropavl'), ('AT', 'Atyrau'), ('AK', 'Aktobe'), ('TZ', 'Taraz'), ('TR', 'Turkostan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title')),
            ],
        ),
        migrations.CreateModel(
            name='ok_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok_answer', models.CharField(max_length=200)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
    ]
