# Generated by Django 2.2 on 2019-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ok_answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='region',
            field=models.CharField(choices=[('NS', 'Nur-Sultan'), ('AT', 'Aktau'), ('AL', 'Almaty'), ('SH', 'Shymkent'), ('KO', 'Kyzylorda'), ('KR', 'Karaganda'), ('ZK', 'Zhezkazgan'), ('KT', 'Kokshetau'), ('ZO', 'Zhanaozen'), ('OS', 'Oskemen'), ('OL', 'Oral'), ('SM', 'Semey'), ('PV', 'Pavlodar'), ('PT', 'Petropavl'), ('AT', 'Atyrau'), ('AK', 'Aktobe'), ('TZ', 'Taraz'), ('TR', 'Turkistan')], max_length=20),
        ),
    ]
