# Generated by Django 2.2 on 2019-04-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190428_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profileDetails',
            new_name='profileDetail',
        ),
    ]
