# Generated by Django 2.2 on 2019-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190428_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
