# Generated by Django 2.2 on 2019-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190428_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profiledetail',
            name='region',
            field=models.CharField(choices=[('NS', 'Nur-Sultan'), ('AL', 'Almaty'), ('SH', 'Shymkent'), ('AT', 'Aktau'), ('AK', 'Aktobe'), ('AT', 'Atyrau'), ('KR', 'Karaganda'), ('KT', 'Kokshetau'), ('KO', 'Kyzylorda'), ('OL', 'Oral'), ('OS', 'Oskemen'), ('PV', 'Pavlodar'), ('PT', 'Petropavl'), ('SM', 'Semey'), ('TZ', 'Taraz'), ('TR', 'Turkistan'), ('ZO', 'Zhanaozen'), ('ZK', 'Zhezkazgan')], default='Nur-Sultan', max_length=20),
        ),
    ]
