# Generated by Django 2.2 on 2019-05-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profiledetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='region',
            field=models.CharField(choices=[('NS', 'Nur-Sultan'), ('AL', 'Almaty'), ('SH', 'Shymkent'), ('AKT', 'Aktau'), ('AK', 'Aktobe'), ('AT', 'Atyrau'), ('KR', 'Karaganda'), ('KT', 'Kokshetau'), ('KO', 'Kyzylorda'), ('OL', 'Oral'), ('OS', 'Oskemen'), ('PV', 'Pavlodar'), ('PT', 'Petropavl'), ('SM', 'Semey'), ('TZ', 'Taraz'), ('TR', 'Turkistan'), ('ZO', 'Zhanaozen'), ('ZK', 'Zhezkazgan')], default='Nur-Sultan', max_length=20),
        ),
    ]
