# Generated by Django 2.2 on 2019-05-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190503_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Title'),
        ),
    ]
