# Generated by Django 2.2 on 2019-05-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190509_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ok_answer',
            name='title',
        ),
    ]
