# Generated by Django 2.2 on 2019-05-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_ok_answer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ok_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okanswers', to='api.Question'),
        ),
    ]
