# Generated by Django 2.2 on 2019-05-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190512_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ok_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quesId', to='api.Question'),
        ),
    ]
